import Head from 'next/head'
import Image from 'next/image'
import Avatar from '../components/Avatar'
import { ViewGridIcon, MicrophoneIcon } from '@heroicons/react/solid'
import { SearchIcon } from '@heroicons/react/outline'
import Footer from '../components/Footer'
import { useRouter } from 'next/router'
import { useRef } from 'react'

export default function Home() {
    const router = useRouter()
    const searchInputRef = useRef(null)
    useRouter
    const search = (e) => {
        e.preventDefault()
        const term = searchInputRef.current.value
        if (!term) return
        router.push(`/search?term=${term}`)
    }
    return (
        <div className='flex flex-col items-center justify-center h-screen'>
            <Head>
                <title>Google Clone</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            {/* Header */}
            <header className='flex w-full p-5 justify-between text-sm text-gray-700'>
                {/* Left */}
                <div className='flex space-x-4 items-center'>
                    <p className='link'>About </p>
                    <p className='link'>Store</p>
                </div>
                {/* Right */}
                <div className='flex space-x-4 items-center'>
                    <p className='link'>Gmail </p>
                    <p className='link'>Images</p>
                    <ViewGridIcon className='w-10 h-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer' />
                    <Avatar
                        url={
                            'https://media-exp1.licdn.com/dms/image/C4E03AQGG43cE_CNw-g/profile-displayphoto-shrink_800_800/0/1637096643728?e=1643846400&v=beta&t=rkZBYo3GJ739IRi3bS-QQcJOKojXH0qqkdjLSVl6woE'
                        }
                    />
                </div>
            </header>

            {/* Body */}
            <form className='flex flex-col items-center mt-44 flex-grow w-4/5'>
                <Image
                    src='https://www.google.com.mx/images/branding/googlelogo/2x/googlelogo_color_160x56dp.png'
                    height={100}
                    width={300}
                    alt='Google Logo'
                />
                <div className='flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border px-5 py-3 items-center border-gray-200 sm:max-w-xl lg:max-w-2xl'>
                    <SearchIcon className='h-5 mr-3 text-gray-500' />
                    <input
                        ref={searchInputRef}
                        type='text'
                        defaultValue={router.query.term}
                        className='focus:outline-none flex-grow'
                    />
                    <MicrophoneIcon className='h-5 mr-3 text-gray-500' />
                </div>

                <div
                    className='flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 
                sm:flex-row sm:space-x-4'>
                    <button onClick={search} className='btn'>
                        Google Search
                    </button>
                    <button onClick={search} className='btn'>
                        I`m Feelings Lucky
                    </button>
                </div>
            </form>

            <Footer />
        </div>
    )
}
